export const ORDER_COMMIT_KIND = {
  BASELINE: "BASELINE",
} as const;

export const ORDER_COMMIT_STATUS = {
  COMMITTED: "COMMITTED",
} as const;

export const ORDER_COMMIT_SNAPSHOT_VERSION = 1;

export const ORDER_COMMIT_SNAPSHOT_SCHEMA_VERSION = "order_commit_snapshot_v1";

export const ORDER_COMMIT_SNAPSHOT_CURRENCY = "KWD";

export const ORDER_COMMIT_SNAPSHOT_LINE_KIND = {
  PACKAGE: "PACKAGE",
  ADD_ON: "ADD_ON",
  PACKAGE_ITEM_UPGRADE: "PACKAGE_ITEM_UPGRADE",
  SELECTED_PHOTO_EXTRA: "SELECTED_PHOTO_EXTRA",
  SESSION_CONFIGURATION: "SESSION_CONFIGURATION",
  LINKED_PRODUCT_SESSION_CONFIGURATION_ADD_ON:
    "LINKED_PRODUCT_SESSION_CONFIGURATION_ADD_ON",
} as const;

export const ORDER_COMMIT_ORDER_ENTITY_KIND = {
  ORDER_PACKAGE: "ORDER_PACKAGE",
  ORDER_ADD_ON: "ORDER_ADD_ON",
  ORDER_PACKAGE_ITEM_UPGRADE: "ORDER_PACKAGE_ITEM_UPGRADE",
  ORDER_PACKAGE_PHOTO_EXTRA: "ORDER_PACKAGE_PHOTO_EXTRA",
  ORDER_PACKAGE_SESSION_CONFIGURATION_SELECTION:
    "ORDER_PACKAGE_SESSION_CONFIGURATION_SELECTION",
} as const;

export const ORDER_COMMIT_PRICE_SOURCE = {
  ORDER_ROW_SNAPSHOT: "ORDER_ROW_SNAPSHOT",
  SESSION_TYPE_EXTRA_PHOTO_PRICING: "SESSION_TYPE_EXTRA_PHOTO_PRICING",
  SESSION_CONFIGURATION_SELECTION_SNAPSHOT:
    "SESSION_CONFIGURATION_SELECTION_SNAPSHOT",
} as const;
