export const ORDER_COMMIT_PREVIEW_BASELINE_SOURCE = {
  LATEST_ORDER_COMMIT: "LATEST_ORDER_COMMIT",
  ORIGINAL_ORDER_COMPOSITION: "ORIGINAL_ORDER_COMPOSITION",
  EMPTY: "EMPTY",
} as const;

export const ORDER_COMMIT_PREVIEW_LINE_CHANGE_KIND = {
  ADDED: "ADDED",
  REMOVED: "REMOVED",
  QUANTITY_CHANGED: "QUANTITY_CHANGED",
  PRICE_CHANGED: "PRICE_CHANGED",
  PACKAGE_CHANGED: "PACKAGE_CHANGED",
  METADATA_CHANGED: "METADATA_CHANGED",
  UNCHANGED: "UNCHANGED",
} as const;

export const ORDER_COMMIT_PREVIEW_COMMIT_KIND = {
  BASE_INVOICE: "BASE_INVOICE",
  ADJUSTMENT_INVOICE: "ADJUSTMENT_INVOICE",
  CREDIT_NOTE: "CREDIT_NOTE",
  REFUND_NEEDED: "REFUND_NEEDED",
  ZERO_NET_AUDIT: "ZERO_NET_AUDIT",
  NO_OP: "NO_OP",
} as const;

export const ORDER_COMMIT_PREVIEW_DOCUMENT_PLAN_KIND = {
  BASE_INVOICE: "BASE_INVOICE",
  FINAL_INVOICE_REBUILD: "FINAL_INVOICE_REBUILD",
  ADJUSTMENT_INVOICE: "ADJUSTMENT_INVOICE",
  CREDIT_NOTE: "CREDIT_NOTE",
  REFUND_NEEDED: "REFUND_NEEDED",
  ZERO_NET_AUDIT_COMMIT: "ZERO_NET_AUDIT_COMMIT",
  NO_OP: "NO_OP",
} as const;

export const ORDER_COMMIT_PREVIEW_PAYMENT_IMPACT_KIND = {
  NONE: "NONE",
  PAYMENT_DUE: "PAYMENT_DUE",
  CREDIT_AVAILABLE: "CREDIT_AVAILABLE",
  REFUND_REVIEW_NEEDED: "REFUND_REVIEW_NEEDED",
} as const;
