export const ORDER_COMMIT_DRAFT_PENDING_OPS_SCHEMA_VERSION =
  "order_commit_draft_pending_ops_v1";

export const ORDER_COMMIT_DRAFT_STAGING_HISTORY_SCHEMA_VERSION =
  "order_commit_draft_staging_history_v1";

export const ORDER_COMMIT_DRAFT_OPERATION_TYPE = {
  SNAPSHOT_REPLACED: "SNAPSHOT_REPLACED",
  NOTE_APPENDED: "NOTE_APPENDED",
} as const;

export const ORDER_COMMIT_DRAFT_STAGING_DOMAIN = {
  PACKAGE: "PACKAGE",
  ADD_ON: "ADD_ON",
  PACKAGE_ITEM_UPGRADE: "PACKAGE_ITEM_UPGRADE",
  PHOTO: "PHOTO",
  SESSION_CONFIGURATION: "SESSION_CONFIGURATION",
} as const;
