ALTER TYPE "OrderActivityType" ADD VALUE IF NOT EXISTS 'ORDER_PACKAGE_ADDED';
ALTER TYPE "OrderActivityType" ADD VALUE IF NOT EXISTS 'ORDER_PACKAGE_LINE_CHANGED';
ALTER TYPE "OrderActivityType" ADD VALUE IF NOT EXISTS 'ORDER_PACKAGE_EXTRAS_CHANGED';
