import { spawnSync } from "node:child_process";

const files = [
  "tests/architecture/deposit-terminology.test.ts",
  "tests/architecture/financial-case-read-layer-cleanup.test.ts",
  "tests/architecture/service-only-db-access.test.ts",
  "tests/bookings/booking-financial-section.test.tsx",
  "tests/bookings/booking-workflow-policy.test.ts",
  "tests/bookings/deposit-invoice-canonicalization.test.ts",
  "tests/composition-view/composition-view.model.test.ts",
  "tests/composition-view/current-composition-card.test.tsx",
  "tests/financial/financial-case-payment-status.test.ts",
  "tests/financial/financial-case-summary/projection-parity-r1b.test.ts",
  "tests/financial/financial-case-summary/projection-parity.test.ts",
  "tests/financial/financial-case-summary/summary-core.test.ts",
  "tests/formatting/money-regression.test.ts",
  "tests/formatting/money.test.ts",
  "tests/session-configurations/session-configuration-selection-service.test.ts",
  "tests/order-commits/order-commit-contracts.test.ts",
  "tests/order-commits/order-commit-add-on-reducer.test.ts",
  "tests/order-commits/order-commit-package-reducer.test.ts",
  "tests/order-commits/order-commit-package-item-upgrade-reducer.test.ts",
  "tests/order-commits/order-commit-photo-reducer.test.ts",
  "tests/order-commits/order-commit-session-configuration-reducer.test.ts",
  "tests/order-commits/order-commit-staging-regression.test.ts",
  "tests/order-commits/order-commit-draft-contracts.test.ts",
  "tests/order-commits/order-commit-preview-contracts.test.ts",
  "tests/order-commits/order-commit-preview-baseline.test.ts",
  "tests/order-commits/order-commit-preview-diff.test.ts",
  "tests/order-commits/order-commit-preview-classification.test.ts",
  "tests/order-commits/order-commit-approval-document-preview.test.ts",
  "tests/order-commits/order-commit-preview-loader.test.ts",
  "tests/order-commits/order-commit-execution-schema.test.ts",
  "tests/order-commits/order-commit-materialization.test.ts",
  "tests/order-commits/order-commit-financial-emission.test.ts",
  "tests/order-commits/order-commit-invoice-emission.test.ts",
  "tests/order-commits/order-commit-document-writer.test.ts",
  "tests/order-commits/order-commit-execution.test.ts",
  "tests/order-commits/order-commit-locked-parity.test.ts",
  "tests/order-commits/sales-staging-actions/stage-happy-path.test.ts",
  "tests/order-commits/sales-staging-actions/stage-lazy-creation.test.ts",
  "tests/order-commits/sales-staging-actions/stage-stale-version.test.ts",
  "tests/order-commits/sales-staging-actions/stage-non-owner.test.ts",
  "tests/order-commits/sales-staging-actions/discard-happy-path.test.ts",
  "tests/order-commits/sales-staging-actions/discard-stale-version.test.ts",
  "tests/order-commits/sales-commit-actions/sales-commit-actions.test.ts",
  "tests/order-commits/sales-commit-dialog/order-commit-review-dialog.test.tsx",
  "tests/order-commits/sales-commit-dialog/order-commit-review-dialog-behavior.test.tsx",
  "tests/order-commits/sales-page-view/sales-page-view-projectors.test.ts",
  "tests/order-commits/sales-page-view/sales-page-view-loader.test.ts",
  "tests/order-commits/sales-page-surface/sales-staging-handler-adapter.test.ts",
  "tests/order-commits/sales-page-surface/session-configuration-staging.test.ts",
  "tests/order-commits/sales-page-surface/sales-draft-ownership-policy.test.ts",
  "tests/order-commits/sales-page-surface/sales-page-view-page-mount.test.ts",
  "tests/order-commits/sales-page-surface/order-commit-financial-sidebar.test.tsx",
  "tests/order-commits/sales-page-surface/pos-record-payment-dialog.test.tsx",
  "tests/order-commits/order-commit-service.test.ts",
  "tests/order-commits/order-commit-snapshot-capture.test.ts",
  "tests/order-commits/order-commit-snapshot-normalizer.test.ts",
  "tests/orders/canonical-balance-display.test.ts",
  "tests/orders/centralization-cleanup.test.ts",
  "tests/orders/commercial-actions-add-on-catalog-parity.test.tsx",
  "tests/orders/customer-order-history-projection.test.ts",
  "tests/orders/delivery-workflow-policy.test.ts",
  "tests/orders/deposit-terminology-render.test.tsx",
  "tests/orders/edit-mode-interactivity-parity.test.tsx",
  "tests/orders/editing-workflow-policy.test.ts",
  "tests/orders/invoice-line-items.test.tsx",
  "tests/orders/operational-configurations-block.test.tsx",
  "tests/orders/order-composition-view-model.test.ts",
  "tests/orders/composition/spec-139-sales-composition-rendering.test.ts",
  "tests/orders/order-details-financials-tab.test.tsx",
  "tests/orders/order-edit-mode-policy.test.ts",
  "tests/orders/order-commit-draft-guard/legacy-mutators-refuse-when-draft-exists.test.ts",
  "tests/orders/order-commit-draft-guard/legacy-mutators-pass-without-draft.test.ts",
  "tests/orders/order-commit-draft-guard/aw-hide-and-freeze-source-guard.test.ts",
  "tests/orders/order-commit-draft-guard/guard-runs-before-lock-check.test.ts",
  "tests/orders/orders-table.test.tsx",
  "tests/orders/pos-handler-components.test.tsx",
  "tests/orders/production-workflow-policy.test.ts",
  "tests/orders/settlement-summary.test.ts",
  "tests/integration/pos-reductive-approval.test.ts",
  "tests/orders/orders-table-customer-history-parity.test.ts",
  "tests/orders/workflow-action-availability-parity.test.ts",
];

const result = spawnSync(
  "node",
  ["--import", "tsx", "--test", "--test-concurrency=1", "--test-force-exit", ...files],
  { stdio: "inherit" }
);

process.exit(result.status ?? 1);
